title: CodingBobby
author: Bob Walter
email: codingbobby@posteo.org
description: >-
  Personal blog of Bob, talking about what interests him and what he learned today.
  He is also showing his projects and lists useful resources for developers
  and science students.
baseurl: ""
url: "https://codingbobby.xyz"
twitter_username: BobbyCoding
github_username: CodingBobby

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-katex

sass:
  style: compressed

theme_config:
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

goat_counter: "codingbobby"
permalink: /blog/:slug/

favicon: "./favicon.png"

staticman_url: https://codingbobby-staticman.herokuapp.com/v2/entry/CodingBobby/codingbobby.github.io/master/comments

katex:
  math_engine: null
  rendering_options:
    throw_error: true
    error_color: "#cc0000"

collections:
  attractors:
    output: true
    permalink: /projects/chaotic-shapes/:name/
